name: Push Folder to GitHub Pages

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.COPY }}
        src_path: Models/
        src_branch: main
        dst_path: /docs/TTS/
        dst_owner: SapphireLab
        dst_branch: main
        dst_repo_name: SapphireLab.github.io